### ici mettre l'url de la base de données postgresql
### exemple => jdbc:postgresql://localhost:5432/mini_learning_tracker
spring.datasource.url=${SPRING_DATASOURCE_URL}

### ### ici mettre le nom de l'utlisateur de la base de données postgresql
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

### ### ici mettre le mot de passe de l'utlisateur de la base de données postgresql
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}